/*
 *  This is a Supplemental File from the Main Project used
 *  in Java Programming Core Fundamental II
 *  with FGroupIndonesia team.
 */
package sesi08;

import sesi04.homework.*;
import sesi04.*;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author ASUS
 */
public class FrameDapurLogin extends javax.swing.JFrame {

    int coba = 0;
    String emailTujuan, dataLogin;

    /**
     * Creates new form FrameAwal
     */
    public FrameDapurLogin() {
        initComponents();
    }

    private boolean isEmpty(JTextField comp) {
        return !(comp.getText().length() > 1);
    }

    private void toggleButtonLogin() {

        // jika kosong maka buttonLogin pun mati alias tidak bisa di click
        if (isEmpty(textfieldPassword) && isEmpty(textfieldUsername)) {
            buttonLogin.setEnabled(false);
        } else {
            buttonLogin.setEnabled(true);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        textfieldUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        textfieldPassword = new javax.swing.JTextField();
        labelForgotPass = new javax.swing.JLabel();
        buttonLogin = new javax.swing.JButton();
        labelPicture = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cridentials", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 16))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        jLabel2.setText("Username :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 45, -1, -1));

        textfieldUsername.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        textfieldUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textfieldUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textfieldUsernameFocusLost(evt);
            }
        });
        textfieldUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textfieldUsernameKeyTyped(evt);
            }
        });
        jPanel1.add(textfieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 79, 240, -1));

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        jLabel1.setText("Password:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        textfieldPassword.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        textfieldPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textfieldPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textfieldPasswordFocusLost(evt);
            }
        });
        textfieldPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textfieldPasswordKeyTyped(evt);
            }
        });
        jPanel1.add(textfieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 240, -1));

        labelForgotPass.setForeground(new java.awt.Color(51, 51, 255));
        labelForgotPass.setText("Forgot Password?");
        labelForgotPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelForgotPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelForgotPassMouseClicked(evt);
            }
        });
        jPanel1.add(labelForgotPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 110, -1));

        buttonLogin.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        buttonLogin.setText("Login");
        buttonLogin.setEnabled(false);
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });
        jPanel1.add(buttonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 208, 90, 40));

        labelPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sesi04/images/food.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(labelPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textfieldUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textfieldUsernameFocusGained
        textfieldUsername.setBackground(Color.yellow);

    }//GEN-LAST:event_textfieldUsernameFocusGained

    private void textfieldUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textfieldUsernameFocusLost
        textfieldUsername.setBackground(null);

    }//GEN-LAST:event_textfieldUsernameFocusLost

    private void textfieldPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textfieldPasswordFocusGained
        // TODO add your handling code here:
        textfieldPassword.setBackground(Color.yellow);
    }//GEN-LAST:event_textfieldPasswordFocusGained

    private void textfieldPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textfieldPasswordFocusLost
        textfieldPassword.setBackground(null);
    }//GEN-LAST:event_textfieldPasswordFocusLost

    private void textfieldUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfieldUsernameKeyTyped
        toggleButtonLogin();
    }//GEN-LAST:event_textfieldUsernameKeyTyped

    private void textfieldPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfieldPasswordKeyTyped
        toggleButtonLogin();
    }//GEN-LAST:event_textfieldPasswordKeyTyped

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        // Menampilkan frame home dan meniadakan
        // frame login tadi (awal)
        /*
        FrameDapurHome penampilan = new FrameDapurHome(this);
        penampilan.setVisible(true);
        this.setVisible(false);
         */

        loginAttempt();


    }//GEN-LAST:event_buttonLoginActionPerformed


    private void labelForgotPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelForgotPassMouseClicked

        String emailMasuk = JOptionPane.showInputDialog("Masukkan email anda :");

        // emailTujuan maupun dataLogin otomatis dpt nilainya
        // ketika pemanggilan method searchDatabase
        
        boolean cari = searchDatabase(emailMasuk);

        if (cari) {
            // kirim ke email ketika email ditemukan
            // gunakan bufferedReader chap.03

            PraktekEmail mesinEmail = new PraktekEmail();
            mesinEmail.sendTo(emailTujuan, "Login Recovery Anda", dataLogin);
            
        } else {

            // jika pencarian failed 
            // maka popup error saja
            JOptionPane.showMessageDialog(null, "Email registered Login not found!",
                    "System", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_labelForgotPassMouseClicked

    private boolean searchDatabase(String emailDicari) {

        boolean hasilKetemu = false;
        BufferedReader buff = null;
        try {

            // tuliskan pembacaan terhadap file database-sederhana.inf
            // lakukan iterasi while dan if else  disini (check chap.03)
            File tujuanFile = new File("database-sederhana.inf");
            buff = new BufferedReader(new FileReader(tujuanFile));
            String terbaca;

            while ((terbaca = buff.readLine()) != null) {
                // proses pemecahan dan pembagian

                String dataBaris[] = terbaca.split(";");
                String usName = dataBaris[0];
                String pass = dataBaris[1];
                String email = dataBaris[2];
                
                emailTujuan = email;
                dataLogin = "Login anda sebenarnya yaitu " +
                        "\nusername :" + usName +
                        "\npass :" + pass;
                
                if(email.equalsIgnoreCase(emailDicari)){
                    hasilKetemu = true;
                    break;
                }

            }

        } catch (Exception ex) {

        }

        return hasilKetemu;

    }

    private void loginAttempt() {

        coba++;

        // get input dari kedua textfield
        // simpen ke string
        String username = textfieldUsername.getText();
        String pass = textfieldPassword.getText();

        if (coba < 3) {
            // coba blm mncapai 3, maka check login admin bukan?
            if (username.equalsIgnoreCase("admin") && pass.equalsIgnoreCase("admin")) {

                FrameDapurHome frameSelanjutnya = new FrameDapurHome();
                frameSelanjutnya.setVisible(true);

            } else {

                JOptionPane.showMessageDialog(null, "Sorry this login is for admin only!!",
                        "Administrator Notification", JOptionPane.ERROR_MESSAGE);

            }

        } else {

            // warning dan kirim email...
            JOptionPane.showMessageDialog(null, "Limit 3x login error!",
                    "Administrator Notification", JOptionPane.ERROR_MESSAGE);

            // send email dari sini
            PraktekEmail machineEmail = new PraktekEmail();
            machineEmail.sendTo("fgroupindonesia@gmail.com", "Notifikasi Login User Salah", "Telah terjadi kesalah login 3x oleh user " + username);
            //machineEmail.sendTo("admin@domainKalian.com");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameDapurLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameDapurLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameDapurLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameDapurLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameDapurLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelForgotPass;
    private javax.swing.JLabel labelPicture;
    private javax.swing.JTextField textfieldPassword;
    private javax.swing.JTextField textfieldUsername;
    // End of variables declaration//GEN-END:variables
}
