/*
 *  This is a Supplemental File from the Main Project used
 *  in Java Programming Core Fundamental II
 *  with FGroupIndonesia team.
 */
package sesi08;

import sesi04.homework.*;
import sesi04.*;
import java.awt.Dimension;

/**
 *
 * @author ASUS
 */
public class FrameDapurHome extends javax.swing.JFrame {

    FrameDapurLogin frameAcuanLogin;
    
    /**
     * Creates new form FrameHome
     */
    public FrameDapurHome() {
        initComponents();
    }

    public FrameDapurHome(FrameDapurLogin frameMasuk){
        frameAcuanLogin = frameMasuk;
        
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCenter = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelLinkAbout = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panelLeft = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelCenter.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panelCenter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("Home");
        panelCenter.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 26, 141, -1));

        labelLinkAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sesi04/images/about16.png"))); // NOI18N
        labelLinkAbout.setText("About");
        labelLinkAbout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelLinkAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelLinkAboutMouseClicked(evt);
            }
        });
        panelCenter.add(labelLinkAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 56, -1, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel2.setText("Catatan : ");
        panelCenter.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 90, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total Cooking", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 16))); // NOI18N
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("76");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel3, java.awt.BorderLayout.CENTER);

        panelCenter.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 158, 203, 152));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total Chef User", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 16))); // NOI18N
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("11");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel4, java.awt.BorderLayout.CENTER);

        panelCenter.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 158, 203, 152));

        jProgressBar1.setValue(45);
        panelCenter.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 424, 40));

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel5.setText("Selamat datang di Dapur Kreatif !");
        panelCenter.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 90, 377, 44));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        panelCenter.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 424, 90));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel6.setText("Progress Bulan ini 45% dari total 100%");
        panelCenter.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 377, 44));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sesi04/images/close.png"))); // NOI18N
        panelCenter.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        getContentPane().add(panelCenter, java.awt.BorderLayout.CENTER);

        panelLeft.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panelLeft.setPreferredSize(new java.awt.Dimension(200, 270));
        panelLeft.setLayout(new java.awt.GridLayout(5, 0));

        jButton2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sesi04/images/chef.png"))); // NOI18N
        jButton2.setText("User");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelLeft.add(jButton2);

        jButton1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sesi04/images/cooking.png"))); // NOI18N
        jButton1.setText("Cooking");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelLeft.add(jButton1);

        jButton3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sesi04/images/option.png"))); // NOI18N
        jButton3.setText("Option");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelLeft.add(jButton3);

        jButton4.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sesi04/images/logout.png"))); // NOI18N
        jButton4.setText("Logout");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelLeft.add(jButton4);

        getContentPane().add(panelLeft, java.awt.BorderLayout.WEST);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void labelLinkAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLinkAboutMouseClicked
        // TODO add your handling code here:
        AboutDialog frame = new AboutDialog(this, true);
        frame.setVisible(true);
        
        
    }//GEN-LAST:event_labelLinkAboutMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        frameAcuanLogin.setVisible(true);
        
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameDapurHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameDapurHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameDapurHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameDapurHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameDapurHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelLinkAbout;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelLeft;
    // End of variables declaration//GEN-END:variables
}
