/*
 *  This is a Supplemental File from the Main Project used
 *  in Java Programming Core Fundamental II
 *  with FGroupIndonesia team.
 */
package sesi04.homework;

import java.awt.Color;
import javax.swing.JTextField;

/**
 *
 * @author ASUS
 */
public class FrameDapurUser extends javax.swing.JFrame {

    /**
     * Creates new form FrameAwal
     */
    public FrameDapurUser() {
        initComponents();
    }

    private boolean isEmpty(JTextField comp) {
        return !(comp.getText().length() > 1);
    }

    private void toggleButtonLogin() {

        // jika kosong maka buttonLogin pun mati alias tidak bisa di click
        if (isEmpty(textfieldPassword) && isEmpty(textfieldUsername)) {
            buttonSave.setEnabled(false);
        } else {
            buttonSave.setEnabled(true);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        textfieldUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        textfieldPassword = new javax.swing.JTextField();
        buttonSave = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        textfieldUsername1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textfieldUsername2 = new javax.swing.JTextField();
        labelPicture = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cridentials", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 16))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        jLabel2.setText("Username :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 45, -1, -1));

        textfieldUsername.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        textfieldUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textfieldUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textfieldUsernameFocusLost(evt);
            }
        });
        textfieldUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textfieldUsernameKeyTyped(evt);
            }
        });
        jPanel1.add(textfieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 79, 240, -1));

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        jLabel1.setText("Password:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        textfieldPassword.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        textfieldPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textfieldPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textfieldPasswordFocusLost(evt);
            }
        });
        textfieldPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textfieldPasswordKeyTyped(evt);
            }
        });
        jPanel1.add(textfieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 240, -1));

        buttonSave.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        buttonSave.setText("Save");
        buttonSave.setEnabled(false);
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });
        jPanel1.add(buttonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 90, 40));

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sesi04/images/telkomsel.png"))); // NOI18N
        jLabel3.setText("Phone Number :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        textfieldUsername1.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        textfieldUsername1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textfieldUsername1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textfieldUsername1FocusLost(evt);
            }
        });
        textfieldUsername1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textfieldUsername1KeyTyped(evt);
            }
        });
        jPanel1.add(textfieldUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 240, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        jLabel4.setText("Minimum Order :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        textfieldUsername2.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        textfieldUsername2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textfieldUsername2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textfieldUsername2FocusLost(evt);
            }
        });
        textfieldUsername2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textfieldUsername2KeyTyped(evt);
            }
        });
        jPanel1.add(textfieldUsername2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 240, -1));

        labelPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sesi04/images/chef.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(labelPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textfieldUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textfieldUsernameFocusGained
        textfieldUsername.setBackground(Color.yellow);

    }//GEN-LAST:event_textfieldUsernameFocusGained

    private void textfieldUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textfieldUsernameFocusLost
        textfieldUsername.setBackground(null);

    }//GEN-LAST:event_textfieldUsernameFocusLost

    private void textfieldPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textfieldPasswordFocusGained
        // TODO add your handling code here:
        textfieldPassword.setBackground(Color.yellow);
    }//GEN-LAST:event_textfieldPasswordFocusGained

    private void textfieldPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textfieldPasswordFocusLost
        textfieldPassword.setBackground(null);
    }//GEN-LAST:event_textfieldPasswordFocusLost

    private void textfieldUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfieldUsernameKeyTyped
        toggleButtonLogin();
    }//GEN-LAST:event_textfieldUsernameKeyTyped

    private void textfieldPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfieldPasswordKeyTyped
        toggleButtonLogin();
    }//GEN-LAST:event_textfieldPasswordKeyTyped

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        // Menampilkan frame home dan meniadakan
        // frame login tadi (awal)
      
        
        
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void textfieldUsername1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textfieldUsername1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldUsername1FocusGained

    private void textfieldUsername1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textfieldUsername1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldUsername1FocusLost

    private void textfieldUsername1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfieldUsername1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldUsername1KeyTyped

    private void textfieldUsername2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textfieldUsername2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldUsername2FocusGained

    private void textfieldUsername2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textfieldUsername2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldUsername2FocusLost

    private void textfieldUsername2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfieldUsername2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldUsername2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameDapurUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameDapurUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameDapurUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameDapurUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameDapurUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelPicture;
    private javax.swing.JTextField textfieldPassword;
    private javax.swing.JTextField textfieldUsername;
    private javax.swing.JTextField textfieldUsername1;
    private javax.swing.JTextField textfieldUsername2;
    // End of variables declaration//GEN-END:variables
}
